version: '3.9'
services:
  postgres:
    image: postgres:14-alpine
    ports:
      - '8080:8080'
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=9mREsvXDs9G89Ef
